name: 🚀 Build and Deploy

on:
  workflow_dispatch:
    inputs:
      lt_version:
        description: "LanguageTool version (e.g. 6.8)"
        required: true
        default: "6.8"
        type: string

jobs:
  deploy:
    name: 🚀 Build, Push & Deploy
    uses: devidence-dev/workflows/.github/workflows/cd-build-deploy-manual-version.yml@v1
    with:
      app_name: languagetool
      version: ${{ inputs.lt_version }}
      version_pattern: '^[0-9]+\.[0-9]+(\.[0-9]+)?$'
      build_args: "LT_VERSION=${{ inputs.lt_version }}"
      values_path: kubernetes/internal-apps/languagetool/values.yaml
    secrets:
      HOMELAB_DEPLOY_TOKEN: ${{ secrets.HOMELAB_DEPLOY_TOKEN }}
    permissions:
      contents: read
      id-token: write
